[package]
name = "kawoof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fallible-iterator = "0.3.0"
rocket = "0.5.0"
rusqlite = "0.31.0"
